spring:
  datasource:
    username: atomfeedclient_admin
    password: password
    url: jdbc:postgresql://localhost:54329/atomfeedclient
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/db_migrations.xml
    parameters:
      schemaName: atomfeed

#The bean 'org.springframework.transaction.config.internalTransactionAdvisor', defined in class path resource [org/springframework/transaction/annotation/ProxyTransactionManagementConfiguration.class], could not be registered. A bean with that name has already been defined in null and overriding is disabled.
  main:
    allow-bean-definition-overriding: true

server:
  port: 8090